typography_spectrum: 0.1254885345697403
color:
  brandStrength: 0.732955081621185
  lightness: 0.9548677965067327
  saturation: 0.4086086789611727
  rhythmicContrast: 0.3180605263914913
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
layout_spectrum: 0.6514794377144426
name: The Super Resum√©
title: Pier-Luc Brousseau
description: |-
  w elihw 
  enoemos
   
  maerd

   
  ruoy


   
  dliub


   
  t'nod


   
  uoy


   fI
